version: '2.3'
services:
  api:
    environment:
      - JWT_SECRET=not very secret key
      - FLASK_DEBUG=1
      - FLASK_APP=screening_api.wsgi:app
      - FLASK_ENV=testenv
      - WERKZEUG_RUN_MAIN=true
      - INI_FILE=screening_api/confs/testenv.ini
      - FQDN=api
      - DBBACKEND=postgresql+psycopg2
      - DBHOST=api-postgres
      - DBHOSTNAME=api-postgres
      - DBNAME=screening
      - DBUSER=screening
      - DBPASSWORD=screening
      - REDISDNS=api-redis
      - AWSACCOUNTID=178847878690
      - AWSREGION=us-east-1
      - ENVIRONMENT=docker
      - SERVICE=screening-api
      - BROKERBACKEND=amqp
      - BROKERUSER=rmquser
      - BROKERPASSWORD=rmqpass
      - BROKERHOST=rabbitmq
      - BROKERNAME=rmq
      - BROKERPORT=5672
      - CACHEHOST=api-redis
      - CODEARTIFACT_AUTH_TOKEN
      - TWINE_USERNAME
      - TWINE_PASSWORD
      - TWINE_REPOSITORY_URL
    ports:
      - 5000:80
      - 5678:5678
      - 9001:9001
    image: 178847878690.dkr.ecr.us-east-1.amazonaws.com/screening-api:0.15.3
    build:
      context: ./
      dockerfile: ./docker/Dockerfile.prod
    command: --nodaemon --configuration /etc/supervisor/supervisord.conf
    volumes:
      - ./:/opt1/screening
      - ./etc/supervisor/supervisord.conf:/etc/supervisor/supervisord.conf
      - ./etc/supervisor/conf.d:/etc/supervisor/conf.d
      - ./etc/nginx/nginx.conf:/etc/nginx/nginx.conf
      - ./etc/nginx/conf.d/default.conf:/etc/nginx/conf.d/default.conf
  api-ui:
    ports:
      - 8080:8080
  api-postgres:
    ports:
      - 5432:5432
    environment:
      - POSTGRES_PASSWORD=screening
      - POSTGRES_USER=screening
      - POSTGRES_DB=screening
