version: '3.7'
services:
  api:
    image: 178847878690.dkr.ecr.us-east-1.amazonaws.com/screening-api:0.15.3
    build:
      target: dev
    command: flask run --host=0.0.0.0 --port=80 --eager-loading
    env_file: envs/dev.env
    environment:
      - CODEARTIFACT_AUTH_TOKEN
      - TWINE_USERNAME
      - TWINE_PASSWORD
      - TWINE_REPOSITORY_URL
    volumes:
      - ./:/usr/src/app
      - ./wheelhouse:/tmp/wheelhouse
    ports:
      - 5000:80
      - 5678:5678
    depends_on:
      - api-postgres
      - api-redis
  api-migrate:
    image: 178847878690.dkr.ecr.us-east-1.amazonaws.com/screening-api:0.15.3
    build:
      target: dev
    env_file: envs/dev.env
    environment:
      - CODEARTIFACT_AUTH_TOKEN
      - TWINE_USERNAME
      - TWINE_PASSWORD
      - TWINE_REPOSITORY_URL
    volumes:
      - ./:/usr/src/app
      - ./wheelhouse:/tmp/wheelhouse
    depends_on:
      - api-postgres
      - api-redis
  api-ui:
    image: 178847878690.dkr.ecr.us-east-1.amazonaws.com/swagger-ui:v3.4.0
    environment:
      - API_URL=openapi.json
    volumes:
      - ./screening_api/spec/openapi.json:/usr/share/nginx/html/openapi.json
    ports:
      - 8080:8080
  api-postgres:
    image: 178847878690.dkr.ecr.us-east-1.amazonaws.com/postgres:9.6.5-alpine
    healthcheck:
      test: nc -zv 127.0.0.1 5432
      interval: 15s
    ports:
      - 5432:5432
    environment:
      - POSTGRES_PASSWORD=screening
      - POSTGRES_USER=screening
      - POSTGRES_DB=screening
  api-pgadmin:
    image: 178847878690.dkr.ecr.us-east-1.amazonaws.com/dpage/pgadmin4:3.6
    ports:
      - 15432:80
    environment:
      - PGADMIN_DEFAULT_EMAIL=screening@polestarglobal.com
      - PGADMIN_DEFAULT_PASSWORD=screening
  api-redis:
    image: 178847878690.dkr.ecr.us-east-1.amazonaws.com/redis:3.2.12-alpine
    healthcheck:
      test: nc -zv 127.0.0.1 6379
      interval: 15s
