apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ template "screening-api.fullname" . }}-migrate
  namespace: {{ .Release.Namespace | quote }}
  labels:
    app: {{ template "screening-api.name" . }}
    chart: "{{ .Chart.Name }}-{{ .Chart.Version }}"
    release: "{{ .Release.Name }}"
    heritage: "{{ .Release.Service }}"
    component: migrate
  annotations:
    helm.sh/hook: pre-install,pre-upgrade
    helm.sh/hook-weight: "9"
    helm.sh/hook-delete-policy: hook-succeeded
data:
  INI_FILE: {{ .Values.api.iniFile }}
  {{- if .Values.postgresql.enabled }}
  # PostgreSQL Database
  DBBACKEND: "postgresql+psycopg2"
  DBHOST: "{{ template "screening-api.fullname" . }}-postgresql"
  DBUSER: {{ .Values.postgresql.postgresUser | quote }}
  DBPASSWORD: {{ .Values.postgresql.postgresPassword | quote }}
  DBNAME: {{ .Values.postgresql.postgresDatabase  | quote }}
  {{- else }}
  # External Database
  DBBACKEND: {{ .Values.externalDatabase.backend | quote }}
  DBHOST: {{ .Values.externalDatabase.host | quote }}
  DBUSER: {{ .Values.externalDatabase.username | quote }}
  DBPASSWORD: {{ .Values.externalDatabase.password | quote }}
  DBNAME: {{ .Values.externalDatabase.name  | quote }}
  {{- end }}
