apiVersion: v1
kind: Service
metadata:
  name: {{ template "screening-api.fullname" . }}
  namespace: {{ template "screening-api.namespace" . }}
  labels:
    app: {{ template "screening-api.name" . }}
    chart: "{{ .Chart.Name }}-{{ .Chart.Version }}"
    release: "{{ .Release.Name }}"
    heritage: "{{ .Release.Service }}"
spec:
  type: {{ .Values.service.type }}
  ports:
    - name: http
      port: 80
      targetPort: http
{{- if .Values.service.nodePort }}
      nodePort: {{ .Values.service.nodePort }}
{{- end }}
  selector:
    app: {{ template "screening-api.name" . }}
