version: '2.1'

services:
  sis-api-postgres:
    image: 178847878690.dkr.ecr.us-east-1.amazonaws.com/mdillon/postgis:9.6-alpine
    healthcheck:
      test: nc -zv 127.0.0.1 5432
      interval: 15s

  api-redis:
    image: 178847878690.dkr.ecr.us-east-1.amazonaws.com/redis:3.2.12-alpine
    healthcheck:
      test: nc -zv 127.0.0.1 6379
      interval: 15s

  sis-api:
    healthcheck:
      test: curl --location http://127.0.0.1:8000/admin/
      interval: 30s
      timeout: 20s
      retries: 30
    depends_on:
      api-redis:
        condition: service_healthy
      sis-api-postgres:
        condition: service_healthy
