"""Added unique to screening report

Revision ID: 00457f432986
Revises: 47ac4e55c100
Create Date: 2018-03-09 10:40:10.575386

"""
from alembic import op


# revision identifiers, used by Alembic.
revision = '00457f432986'
down_revision = '47ac4e55c100'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint(None, 'screenings_reports', ['screening_id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'screenings_reports', type_='unique')
    # ### end Alembic commands ###
