"""Removed history severity

Revision ID: 05c51c099250
Revises: 0a1b1a2313c8
Create Date: 2017-12-14 09:58:03.687831

"""
from alembic import op
import sqlalchemy as sa

# revision identifiers, used by Alembic.
revision = '05c51c099250'
down_revision = '0a1b1a2313c8'
branch_labels = None
depends_on = None

severity = sa.Enum(
    'OK', 'WARNING', 'CRITICAL', 'UNKNOWN',
    name='severity',
)


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('screenings_history', 'severity')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        'screenings_history',
        sa.Column('severity', severity, autoincrement=False, nullable=False),
    )
    # ### end Alembic commands ###
