"""Added blacklisted sanction list

Revision ID: 07eca30e65b1
Revises: 876cd219b280
Create Date: 2019-11-06 14:03:43.222351

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '07eca30e65b1'
down_revision = '876cd219b280'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        'blacklisted_sanctions_lists',
        sa.Column('id', sa.Integer(), nullable=False),
        sa.Column('created', sa.DateTime(), nullable=False),
        sa.Column('updated', sa.DateTime(), nullable=False),
        sa.PrimaryKeyConstraint('id'),
    )
    op.create_table(
        'blacklisted_sanctions_lists_items',
        sa.Column('id', sa.Integer(), nullable=False),
        sa.Column('created', sa.DateTime(), nullable=False),
        sa.Column('updated', sa.DateTime(), nullable=False),
        sa.Column(
            'blacklisted_sanction_list_id', sa.Integer(), nullable=False),
        sa.Column('sanction_code', sa.Integer(), nullable=False),
        sa.ForeignKeyConstraint(
            ['blacklisted_sanction_list_id'],
            ['blacklisted_sanctions_lists.id'],
            onupdate='CASCADE', ondelete='CASCADE',
        ),
        sa.PrimaryKeyConstraint('id'),
        sa.UniqueConstraint(
            'blacklisted_sanction_list_id', 'sanction_code',
            name='blacklisted_sanction_list_id_sanction_code_unique',
        ),
    )
    op.create_index(
        op.f(
            'ix_blacklisted_sanctions_lists_items_'
            'blacklisted_sanction_list_id'
        ),
        'blacklisted_sanctions_lists_items',
        ['blacklisted_sanction_list_id'],
        unique=False,
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(
        'blacklisted_sanction_list_id_sanction_code_unique',
        'blacklisted_sanctions_lists_items', type_='unique',
    )
    op.drop_index(
        op.f(
            'ix_blacklisted_sanctions_lists_items_'
            'blacklisted_sanction_list_id'
        ),
        table_name='blacklisted_sanctions_lists_items',
    )
    op.drop_table('blacklisted_sanctions_lists_items')
    op.drop_table('blacklisted_sanctions_lists')
    # ### end Alembic commands ###
