"""Added screening history

Revision ID: 0a1b1a2313c8
Revises: cc7a85a92040
Create Date: 2017-12-04 11:15:36.847623

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql


# revision identifiers, used by Alembic.
revision = '0a1b1a2313c8'
down_revision = 'cc7a85a92040'
branch_labels = None
depends_on = None

severity = postgresql.ENUM(
    'UNKNOWN', 'OK', 'WARNING', 'CRITICAL', name='severity', create_type=False)


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        'screenings_history',
        sa.Column('id', sa.Integer(), nullable=False),
        sa.Column('created', sa.DateTime(), nullable=False),
        sa.Column('updated', sa.DateTime(), nullable=False),
        sa.Column('screening_id', sa.Integer(), nullable=False),
        sa.Column('severity', severity, nullable=False),
        sa.Column('company_sanction_severity', severity, nullable=False),
        sa.Column('ship_association_severity', severity, nullable=False),
        sa.Column('ship_sanction_severity', severity, nullable=False),
        sa.Column('ship_flag_severity', severity, nullable=False),
        sa.Column('ship_registered_owner_severity', severity, nullable=False),
        sa.Column('ship_operator_severity', severity, nullable=False),
        sa.Column('ship_beneficial_owner_severity', severity, nullable=False),
        sa.Column('ship_manager_severity', severity, nullable=False),
        sa.Column('ship_technical_manager_severity', severity, nullable=False),
        sa.Column('doc_company_severity', severity, nullable=False),
        sa.Column('detention_severity', severity, nullable=False),
        sa.Column('deficiency_severity', severity, nullable=False),
        sa.Column('port_visits_severity', severity, nullable=False),
        sa.Column('zone_visits_severity', severity, nullable=False),
        sa.ForeignKeyConstraint(
            ['screening_id'], ['screenings.id'],
            onupdate='CASCADE', ondelete='CASCADE',
        ),
        sa.PrimaryKeyConstraint('id'),
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('screenings_history')
    # ### end Alembic commands ###
