"""Added previous severity in screenings

Revision ID: 139c9492637d
Revises: 640c6fa8cc00
Create Date: 2018-05-14 10:53:00.333026

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '139c9492637d'
down_revision = '640c6fa8cc00'
branch_labels = None
depends_on = None


severity = postgresql.ENUM(
    'OK', 'WARNING', 'CRITICAL', 'UNKNOWN', name='severity', create_type=False)


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        'screenings',
        sa.Column(
            'previous_severity', severity, nullable=False,
            server_default=sa.text("'UNKNOWN'::severity"),
        ),
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('screenings', 'previous_severity')
    # ### end Alembic commands ###
