"""Standardize ship country fields

Revision ID: 2220acf0794d
Revises: fbcd7c95575f
Create Date: 2018-03-27 09:11:43.407220

"""
from alembic import op


# revision identifiers, used by Alembic.
revision = '2220acf0794d'
down_revision = 'fbcd7c95575f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column(
        'ships', 'operator_country_of_domicile_name',
        new_column_name='operator_country_of_domicile',
    )
    op.alter_column(
        'ships', 'ship_manager_country_of_domicile_name',
        new_column_name='ship_manager_country_of_domicile',
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column(
        'ships', 'operator_country_of_domicile',
        new_column_name='operator_country_of_domicile_name',
    )
    op.alter_column(
        'ships', 'ship_manager_country_of_domicile',
        new_column_name='ship_manager_country_of_domicile_name',
    )
    # ### end Alembic commands ###
