"""Adeed previous severity date

Revision ID: 2894d3615d1c
Revises: 139c9492637d
Create Date: 2018-05-15 12:53:27.281787

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '2894d3615d1c'
down_revision = '139c9492637d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        'screenings',
        sa.Column('previous_severity_date', sa.DateTime(), nullable=True),
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('screenings', 'previous_severity_date')
    # ### end Alembic commands ###
