"""Added report fields to screening history

Revision ID: 2cd8a0affae4
Revises: 09d7ed5ddcae
Create Date: 2018-05-04 10:46:45.450833

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '2cd8a0affae4'
down_revision = '09d7ed5ddcae'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        'screenings_history',
        sa.Column('doc_company', sa.JSON(), nullable=True),
    )
    op.add_column(
        'screenings_history',
        sa.Column('port_visits', sa.JSON(), nullable=True),
    )
    op.add_column(
        'screenings_history',
        sa.Column('ship_association', sa.JSON(), nullable=True),
    )
    op.add_column(
        'screenings_history',
        sa.Column('ship_beneficial_owner', sa.JSON(), nullable=True),
    )
    op.add_column(
        'screenings_history',
        sa.Column('ship_beneficial_owner_company', sa.JSON(), nullable=True),
    )
    op.add_column(
        'screenings_history',
        sa.Column('ship_company_associates', sa.JSON(), nullable=True),
    )
    op.add_column(
        'screenings_history',
        sa.Column('ship_flag', sa.JSON(), nullable=True),
    )
    op.add_column(
        'screenings_history',
        sa.Column('ship_inspections', sa.JSON(), nullable=True),
    )
    op.add_column(
        'screenings_history',
        sa.Column('ship_manager', sa.JSON(), nullable=True),
    )
    op.add_column(
        'screenings_history',
        sa.Column('ship_manager_company', sa.JSON(), nullable=True),
    )
    op.add_column(
        'screenings_history',
        sa.Column('ship_operator', sa.JSON(), nullable=True),
    )
    op.add_column(
        'screenings_history',
        sa.Column('ship_operator_company', sa.JSON(), nullable=True),
    )
    op.add_column(
        'screenings_history',
        sa.Column('ship_registered_owner', sa.JSON(), nullable=True),
    )
    op.add_column(
        'screenings_history',
        sa.Column('ship_registered_owner_company', sa.JSON(), nullable=True),
    )
    op.add_column(
        'screenings_history',
        sa.Column('ship_sanction', sa.JSON(), nullable=True),
    )
    op.add_column(
        'screenings_history',
        sa.Column('ship_technical_manager', sa.JSON(), nullable=True),
    )
    op.add_column(
        'screenings_history',
        sa.Column('ship_technical_manager_company', sa.JSON(), nullable=True),
    )
    op.add_column(
        'screenings_history',
        sa.Column('zone_visits', sa.JSON(), nullable=True),
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('screenings_history', 'zone_visits')
    op.drop_column('screenings_history', 'ship_technical_manager_company')
    op.drop_column('screenings_history', 'ship_technical_manager')
    op.drop_column('screenings_history', 'ship_sanction')
    op.drop_column('screenings_history', 'ship_registered_owner_company')
    op.drop_column('screenings_history', 'ship_registered_owner')
    op.drop_column('screenings_history', 'ship_operator_company')
    op.drop_column('screenings_history', 'ship_operator')
    op.drop_column('screenings_history', 'ship_manager_company')
    op.drop_column('screenings_history', 'ship_manager')
    op.drop_column('screenings_history', 'ship_inspections')
    op.drop_column('screenings_history', 'ship_flag')
    op.drop_column('screenings_history', 'ship_company_associates')
    op.drop_column('screenings_history', 'ship_beneficial_owner_company')
    op.drop_column('screenings_history', 'ship_beneficial_owner')
    op.drop_column('screenings_history', 'ship_association')
    op.drop_column('screenings_history', 'port_visits')
    op.drop_column('screenings_history', 'doc_company')
    # ### end Alembic commands ###
