"""Added screenings indexes

Revision ID: 3b933a9de9dd
Revises: c9fbb9be81b4
Create Date: 2018-08-29 08:28:39.767836

"""
from alembic import op


# revision identifiers, used by Alembic.
revision = '3b933a9de9dd'
down_revision = 'c9fbb9be81b4'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index(
        op.f('ix_screenings_account_id'), 'screenings',
        ['account_id'], unique=False,
    )
    op.create_index(
        op.f('ix_screenings_company_sanctions_severity'), 'screenings',
        ['company_sanctions_severity'], unique=False,
    )
    op.create_index(
        op.f('ix_screenings_country_sanctions_severity'), 'screenings',
        ['country_sanctions_severity'], unique=False,
    )
    op.create_index(
        'ix_screenings_created', 'screenings',
        ['created'], unique=False,
    )
    op.create_index(
        'ix_screenings_ship_inspections_severity', 'screenings',
        ['ship_inspections_severity'], unique=False,
    )
    op.create_index(
        op.f('ix_screenings_severity'), 'screenings',
        ['severity'], unique=False,
    )
    op.create_index(
        op.f('ix_screenings_severity_change'), 'screenings',
        ['severity_change'], unique=False,
    )
    op.create_index(
        op.f('ix_screenings_ship_movements_severity'), 'screenings',
        ['ship_movements_severity'], unique=False,
    )
    op.create_index(
        op.f('ix_screenings_ship_sanctions_severity'), 'screenings',
        ['ship_sanctions_severity'], unique=False,
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(
        op.f('ix_screenings_ship_sanctions_severity'),
        table_name='screenings',
    )
    op.drop_index(
        op.f('ix_screenings_ship_movements_severity'),
        table_name='screenings',
    )
    op.drop_index(
        op.f('ix_screenings_severity_change'),
        table_name='screenings',
    )
    op.drop_index(
        op.f('ix_screenings_severity'),
        table_name='screenings',
    )
    op.drop_index(
        'ix_screenings_created',
        table_name='screenings',
    )
    op.drop_index(
        op.f('ix_screenings_country_sanctions_severity'),
        table_name='screenings',
    )
    op.drop_index(
        op.f('ix_screenings_company_sanctions_severity'),
        table_name='screenings',
    )
    op.drop_index(
        op.f('ix_screenings_account_id'),
        table_name='screenings',
    )
    # ### end Alembic commands ###
