"""Added ship info

Revision ID: 41ee2bc07eef
Revises: c82b952ffa2a
Create Date: 2018-11-20 13:19:52.907336

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '41ee2bc07eef'
down_revision = 'c82b952ffa2a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        'screenings_history',
        sa.Column('ship_info', sa.JSON(), nullable=True),
    )
    op.add_column(
        'screenings_reports',
        sa.Column('ship_info', sa.JSON(), nullable=True),
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('screenings_reports', 'ship_info')
    op.drop_column('screenings_history', 'ship_info')
    # ### end Alembic commands ###
