"""Added severity date

Revision ID: 4228b731adad
Revises: 247e75f5c024
Create Date: 2018-07-26 13:45:25.924198

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '4228b731adad'
down_revision = '247e75f5c024'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        'screenings_history',
        sa.Column('severity_date', sa.DateTime(), nullable=True),
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('screenings_history', 'severity_date')
    # ### end Alembic commands ###
