"""Added mmsi

Revision ID: 47ac4e55c100
Revises: a900dcfb5051
Create Date: 2018-03-08 14:45:29.979874

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '47ac4e55c100'
down_revision = 'a900dcfb5051'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('ships', sa.Column('mmsi', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('ships', 'mmsi')
    # ### end Alembic commands ###
