"""Added country_id to ship

Revision ID: 4c90f6bdccb4
Revises: 9b3997b40790
Create Date: 2017-10-16 13:27:58.768188

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '4c90f6bdccb4'
down_revision = '9b3997b40790'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        'ships',
        sa.Column('country_id', sa.String(), nullable=True),
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('ships', 'country_id')
    # ### end Alembic commands ###
