"""Added country name

Revision ID: 5b0f58bba23d
Revises: 384e96d65cad
Create Date: 2017-10-31 14:05:57.074254

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '5b0f58bba23d'
down_revision = '384e96d65cad'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        'ships',
        sa.Column('country_name', sa.String(), nullable=True),
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('ships', 'country_name')
    # ### end Alembic commands ###
