"""Added ship extra fields

Revision ID: 640c6fa8cc00
Revises: 2cd8a0affae4
Create Date: 2018-05-10 10:39:36.112260

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '640c6fa8cc00'
down_revision = '2cd8a0affae4'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        'ships',
        sa.Column('breadth', sa.Numeric(), nullable=True),
    )
    op.add_column(
        'ships',
        sa.Column('build_country_name', sa.String(), nullable=True),
    )
    op.add_column(
        'ships',
        sa.Column('build_year', sa.Integer(), nullable=True),
    )
    op.add_column(
        'ships',
        sa.Column('call_sign', sa.String(), nullable=True),
    )
    op.add_column(
        'ships',
        sa.Column('classification_society', sa.String(), nullable=True),
    )
    op.add_column(
        'ships',
        sa.Column('country_effective_date', sa.String(), nullable=True),
    )
    op.add_column(
        'ships',
        sa.Column('deadweight', sa.Integer(), nullable=True),
    )
    op.add_column(
        'ships',
        sa.Column('displacement', sa.Integer(), nullable=True),
    )
    op.add_column(
        'ships',
        sa.Column('draught', sa.Numeric(), nullable=True),
    )
    op.add_column(
        'ships',
        sa.Column('pandi_club', sa.String(), nullable=True),
    )
    op.add_column(
        'ships',
        sa.Column('port_of_registry', sa.String(), nullable=True),
    )
    op.add_column(
        'ships', sa.Column('length', sa.Numeric(), nullable=True),
    )
    op.add_column(
        'ships', sa.Column('weight', sa.Integer(), nullable=True),
    )
    op.add_column(
        'ships',
        sa.Column(
            'safety_management_certificate_date_issued', sa.Date(),
            nullable=True,
        ),
    )
    op.add_column(
        'ships',
        sa.Column(
            'safety_management_certificate_doc_company', sa.String(),
            nullable=True,
        ),
    )
    op.add_column(
        'ships',
        sa.Column('shipbuilder', sa.String(), nullable=True),
    )
    op.add_column(
        'ships',
        sa.Column('status', sa.String(), nullable=True),
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('ships', 'status')
    op.drop_column('ships', 'shipbuilder')
    op.drop_column('ships', 'safety_management_certificate_doc_company')
    op.drop_column('ships', 'safety_management_certificate_date_issued')
    op.drop_column('ships', 'weight')
    op.drop_column('ships', 'length')
    op.drop_column('ships', 'port_of_registry')
    op.drop_column('ships', 'pandi_club')
    op.drop_column('ships', 'draught')
    op.drop_column('ships', 'displacement')
    op.drop_column('ships', 'deadweight')
    op.drop_column('ships', 'country_effective_date')
    op.drop_column('ships', 'classification_society')
    op.drop_column('ships', 'call_sign')
    op.drop_column('ships', 'build_year')
    op.drop_column('ships', 'build_country_name')
    op.drop_column('ships', 'breadth')
    # ### end Alembic commands ###
