"""Added company associations

Revision ID: 7b8ffa761138
Revises: c365f35c7a87
Create Date: 2018-05-01 17:45:01.082987

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '7b8ffa761138'
down_revision = 'c365f35c7a87'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        'company_associations',
        sa.Column('id', sa.Integer(), nullable=False),
        sa.Column('created', sa.DateTime(), nullable=False),
        sa.Column('updated', sa.DateTime(), nullable=False),
        sa.Column('src_id', sa.Integer(), nullable=False),
        sa.Column('dst_id', sa.Integer(), nullable=False),
        sa.Column('relationship', sa.String(), nullable=False),
        sa.ForeignKeyConstraint(
            ['dst_id'], ['compliance_companies.id'],
            onupdate='CASCADE', ondelete='CASCADE',
        ),
        sa.ForeignKeyConstraint(
            ['src_id'], ['compliance_companies.id'],
            onupdate='CASCADE', ondelete='CASCADE',
        ),
        sa.PrimaryKeyConstraint('id'),
        sa.UniqueConstraint('src_id', 'dst_id', name='src_id_dst_id_unique'),
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('company_associations')
    # ### end Alembic commands ###
