"""Renamed checks

Revision ID: 8106cba820c1
Revises: d1b5652cb515
Create Date: 2018-02-01 11:35:15.304937

"""
from alembic import op
import sqlalchemy as sa

# revision identifiers, used by Alembic.
revision = '8106cba820c1'
down_revision = 'd1b5652cb515'
branch_labels = None
depends_on = None

severity = sa.Enum('OK', 'WARNING', 'CRITICAL', 'UNKNOWN', name='severity')
status = sa.Enum('CREATED', 'DONE', 'SCHEDULED', 'PENDING', name='status')


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        'screenings',
        sa.Column(
            'company_sanctions_severity', severity,
            nullable=False, server_default='OK',
        ),
    )
    op.add_column(
        'screenings',
        sa.Column(
            'company_sanctions_status', status,
            nullable=False, server_default='DONE',
        ),
    )
    op.drop_column('screenings', 'company_sanction_severity')
    op.drop_column('screenings', 'company_sanction_status')
    op.add_column(
        'screenings_history',
        sa.Column(
            'company_sanctions_severity', severity,
            nullable=False, server_default='OK',
        ),
    )
    op.drop_column('screenings_history', 'company_sanction_severity')

    op.add_column(
        'screenings',
        sa.Column(
            'ship_inspections_severity', severity,
            nullable=False, server_default='OK',
        ),
    )
    op.add_column(
        'screenings',
        sa.Column(
            'ship_inspections_status', status,
            nullable=False, server_default='DONE',
        ),
    )
    op.drop_column('screenings', 'detention_severity')
    op.drop_column('screenings', 'deficiency_severity')
    op.drop_column('screenings', 'deficiency_status')
    op.drop_column('screenings', 'detention_status')
    op.add_column(
        'screenings_history',
        sa.Column(
            'ship_inspections_severity', severity,
            nullable=False, server_default='OK',
        ),
    )
    op.drop_column('screenings_history', 'detention_severity')
    op.drop_column('screenings_history', 'deficiency_severity')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        'screenings_history',
        sa.Column(
            'deficiency_severity', severity,
            nullable=False, server_default='OK',
        ),
    )
    op.add_column(
        'screenings_history',
        sa.Column(
            'detention_severity', severity,
            nullable=False, server_default='OK',
        ),
    )
    op.drop_column('screenings_history', 'ship_inspections_severity')
    op.add_column(
        'screenings',
        sa.Column(
            'detention_status', status,
            nullable=False, server_default='DONE',
        ),
    )
    op.add_column(
        'screenings',
        sa.Column(
            'deficiency_status', status,
            nullable=False, server_default='DONE',
        ),
    )
    op.add_column(
        'screenings',
        sa.Column(
            'deficiency_severity', severity,
            nullable=False, server_default='OK',
        ),
    )
    op.add_column(
        'screenings',
        sa.Column(
            'detention_severity', severity,
            nullable=False, server_default='OK',
        ),
    )
    op.drop_column('screenings', 'ship_inspections_status')
    op.drop_column('screenings', 'ship_inspections_severity')

    op.add_column(
        'screenings_history',
        sa.Column(
            'company_sanction_severity', severity,
            nullable=False, server_default='OK',
        ),
    )
    op.drop_column('screenings_history', 'company_sanctions_severity')
    op.add_column(
        'screenings',
        sa.Column(
            'company_sanction_severity', severity,
            nullable=False, server_default='OK',
        ),
    )
    op.add_column(
        'screenings',
        sa.Column(
            'company_sanction_status', status,
            nullable=False, server_default='DONE',
        ),
    )
    op.drop_column('screenings', 'company_sanctions_status')
    op.drop_column('screenings', 'company_sanctions_severity')
    # ### end Alembic commands ###
