"""Added inspection id and authority

Revision ID: 91e02632f1df
Revises: e0d7ce3f5f34
Create Date: 2018-01-23 13:01:57.120714

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '91e02632f1df'
down_revision = 'e0d7ce3f5f34'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column(
        'ship_inspections', 'inspection_date', type_=sa.Date()),
    op.add_column(
        'ship_inspections',
        sa.Column('authority', sa.String(), nullable=False),
    )
    op.add_column(
        'ship_inspections',
        sa.Column('inspection_id', sa.String(), nullable=False),
    )
    op.create_unique_constraint(None, 'ship_inspections', ['inspection_id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'ship_inspections', type_='unique')
    op.drop_column('ship_inspections', 'inspection_id')
    op.drop_column('ship_inspections', 'authority')
    op.alter_column('ship_inspections', 'inspection_date', type_=sa.DateTime())
    # ### end Alembic commands ###
