"""Added screenings table

Revision ID: 9b3997b40790
Revises: fe192dfb57f2
Create Date: 2017-10-16 10:47:02.924586

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '9b3997b40790'
down_revision = 'fe192dfb57f2'
branch_labels = None
depends_on = None

severity = sa.Enum(
    'UNKNOWN', 'OK', 'WARNING', 'CRITICAL',
    name='severity',
)


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        'screenings',
        sa.Column('id', sa.Integer(), nullable=False),
        sa.Column('created', sa.DateTime(), nullable=False),
        sa.Column('updated', sa.DateTime(), nullable=False),
        sa.Column('ship_id', sa.Integer(), nullable=False),
        sa.Column('account_id', sa.Integer(), nullable=True),
        sa.Column('severity', severity, nullable=False),
        sa.ForeignKeyConstraint(
            ['ship_id'], ['ships.id'],
            onupdate='CASCADE', ondelete='CASCADE',
        ),
        sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('screenings')
    severity.drop(op.get_bind(), checkfirst=False)
    # ### end Alembic commands ###
