"""Added company sanctions columns

Revision ID: a1a469d97e6b
Revises: 063384afd599
Create Date: 2018-04-26 10:43:31.663347

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql


# revision identifiers, used by Alembic.
revision = 'a1a469d97e6b'
down_revision = '063384afd599'
branch_labels = None
depends_on = None

status = postgresql.ENUM(
    'CREATED', 'DONE', 'SCHEDULED', 'PENDING', name='status',
    create_type=False,
)
severity = postgresql.ENUM(
    'OK', 'WARNING', 'CRITICAL', 'UNKNOWN', name='severity', create_type=False)


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('screenings', 'company_sanctions_status')

    op.add_column(
        'screenings',
        sa.Column(
            'ship_beneficial_owner_company_status', status,
            nullable=False, server_default=sa.text("'CREATED'::status"),
        ),
    )
    op.add_column(
        'screenings',
        sa.Column(
            'ship_manager_company_status', status,
            nullable=False, server_default=sa.text("'CREATED'::status"),
        ),
    )
    op.add_column(
        'screenings',
        sa.Column(
            'ship_operator_company_status', status,
            nullable=False, server_default=sa.text("'CREATED'::status"),
        ),
    )
    op.add_column(
        'screenings',
        sa.Column(
            'ship_registered_owner_company_status', status,
            nullable=False, server_default=sa.text("'CREATED'::status"),
        ),
    )
    op.add_column(
        'screenings',
        sa.Column(
            'ship_technical_manager_company_status', status,
            nullable=False, server_default=sa.text("'CREATED'::status"),
        ),
    )

    op.drop_column('screenings', 'company_sanctions_severity')

    op.add_column(
        'screenings',
        sa.Column(
            'ship_beneficial_owner_company_severity', severity,
            nullable=False, server_default=sa.text("'UNKNOWN'::severity"),
        ),
    )
    op.add_column(
        'screenings',
        sa.Column(
            'ship_manager_company_severity', severity,
            nullable=False, server_default=sa.text("'UNKNOWN'::severity"),
        ),
    )
    op.add_column(
        'screenings',
        sa.Column(
            'ship_operator_company_severity', severity,
            nullable=False, server_default=sa.text("'UNKNOWN'::severity"),
        ),
    )
    op.add_column(
        'screenings',
        sa.Column(
            'ship_registered_owner_company_severity', severity,
            nullable=False, server_default=sa.text("'UNKNOWN'::severity"),
        ),
    )
    op.add_column(
        'screenings',
        sa.Column(
            'ship_technical_manager_company_severity', severity,
            nullable=False, server_default=sa.text("'UNKNOWN'::severity"),
        ),
    )

    op.drop_column('screenings_history', 'company_sanctions_severity')

    op.add_column(
        'screenings_history',
        sa.Column(
            'ship_beneficial_owner_company_severity', severity,
            nullable=False, server_default=sa.text("'UNKNOWN'::severity"),
        ),
    )
    op.add_column(
        'screenings_history',
        sa.Column(
            'ship_manager_company_severity', severity,
            nullable=False, server_default=sa.text("'UNKNOWN'::severity"),
        ),
    )
    op.add_column(
        'screenings_history',
        sa.Column(
            'ship_operator_company_severity', severity,
            nullable=False, server_default=sa.text("'UNKNOWN'::severity"),
        ),
    )
    op.add_column(
        'screenings_history',
        sa.Column(
            'ship_registered_owner_company_severity', severity,
            nullable=False, server_default=sa.text("'UNKNOWN'::severity"),
        ),
    )
    op.add_column(
        'screenings_history',
        sa.Column(
            'ship_technical_manager_company_severity', severity,
            nullable=False, server_default=sa.text("'UNKNOWN'::severity"),
        ),
    )

    op.drop_column('screenings_reports', 'company_sanctions')

    op.add_column(
        'screenings_reports',
        sa.Column('ship_beneficial_owner_company', sa.JSON(), nullable=True),
    )
    op.add_column(
        'screenings_reports',
        sa.Column('ship_manager_company', sa.JSON(), nullable=True),
    )
    op.add_column(
        'screenings_reports',
        sa.Column('ship_operator_company', sa.JSON(), nullable=True),
    )
    op.add_column(
        'screenings_reports',
        sa.Column('ship_registered_owner_company', sa.JSON(), nullable=True),
    )
    op.add_column(
        'screenings_reports',
        sa.Column('ship_technical_manager_company', sa.JSON(), nullable=True),
    )

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('screenings_reports', 'ship_technical_manager_company')
    op.drop_column('screenings_reports', 'ship_registered_owner_company')
    op.drop_column('screenings_reports', 'ship_operator_company')
    op.drop_column('screenings_reports', 'ship_manager_company')
    op.drop_column('screenings_reports', 'ship_beneficial_owner_company')

    op.add_column(
        'screenings_reports',
        sa.Column(
            'company_sanctions',
            postgresql.JSON(astext_type=sa.Text()),
            autoincrement=False,
            nullable=True,
        ),
    )

    op.drop_column(
        'screenings_history', 'ship_technical_manager_company_severity')
    op.drop_column(
        'screenings_history', 'ship_registered_owner_company_severity')
    op.drop_column(
        'screenings_history', 'ship_operator_company_severity')
    op.drop_column(
        'screenings_history', 'ship_manager_company_severity')
    op.drop_column(
        'screenings_history', 'ship_beneficial_owner_company_severity')

    op.add_column(
        'screenings_history',
        sa.Column(
            'company_sanctions_severity', severity,
            server_default=sa.text("'OK'::severity"), autoincrement=False,
            nullable=False,
        ),
    )

    op.drop_column('screenings', 'ship_technical_manager_company_status')
    op.drop_column('screenings', 'ship_technical_manager_company_severity')
    op.drop_column('screenings', 'ship_registered_owner_company_status')
    op.drop_column('screenings', 'ship_registered_owner_company_severity')
    op.drop_column('screenings', 'ship_operator_company_status')
    op.drop_column('screenings', 'ship_operator_company_severity')
    op.drop_column('screenings', 'ship_manager_company_status')
    op.drop_column('screenings', 'ship_manager_company_severity')
    op.drop_column('screenings', 'ship_beneficial_owner_company_status')
    op.drop_column('screenings', 'ship_beneficial_owner_company_severity')

    op.add_column(
        'screenings',
        sa.Column(
            'company_sanctions_severity', severity,
            server_default=sa.text("'OK'::severity"), autoincrement=False,
            nullable=False,
        ),
    )
    op.add_column(
        'screenings',
        sa.Column(
            'company_sanctions_status', status,
            server_default=sa.text("'DONE'::status"), autoincrement=False,
            nullable=False,
        ),
    )
    # ### end Alembic commands ###
