"""Update compliance entities

Revision ID: abac0389a3da
Revises: dde1cbcd8a23
Create Date: 2018-05-17 11:05:47.227310

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'abac0389a3da'
down_revision = 'dde1cbcd8a23'
branch_labels = None
depends_on = None


entitytype = sa.Enum(
    'ORGANISATION', 'PERSON', 'SHIP', name='entitytype',
)


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    entitytype.create(op.get_bind())
    op.create_table(
        'compliance_entity_sanctions',
        sa.Column('created', sa.DateTime(), nullable=False),
        sa.Column('updated', sa.DateTime(), nullable=False),
        sa.Column('compliance_sanction_id', sa.Integer(), nullable=False),
        sa.Column('compliance_entity_id', sa.Integer(), nullable=False),
        sa.ForeignKeyConstraint(
            ['compliance_entity_id'], ['compliance_entities.id'],
            onupdate='CASCADE', ondelete='CASCADE',
        ),
        sa.ForeignKeyConstraint(
            ['compliance_sanction_id'], ['compliance_sanctions.id'],
            onupdate='CASCADE', ondelete='CASCADE',
        ),
        sa.PrimaryKeyConstraint(
            'compliance_sanction_id', 'compliance_entity_id',
        ),
        sa.UniqueConstraint(
            'compliance_sanction_id', 'compliance_entity_id',
            name='sanction_id_entity_id',
        )
    )
    op.add_column(
        'compliance_entities',
        sa.Column(
            'entity_type', entitytype, nullable=False,
            server_default=sa.text("'ORGANISATION'::entitytype"),
        ),
    )
    op.add_column(
        'compliance_sanctions',
        sa.Column('compliance_id', sa.Integer(), nullable=False),
    )
    op.drop_constraint(
        'company_id_sanction_list_name', 'compliance_sanctions',
        type_='unique',
    )
    op.create_unique_constraint(
        'company_sanctions_compliance_id_unique', 'compliance_sanctions',
        ['compliance_id'],
    )
    op.drop_constraint(
        'company_sanctions_company_id_fkey', 'compliance_sanctions',
        type_='foreignkey',
    )
    op.drop_column('compliance_sanctions', 'company_id')
    op.add_column(
        'sis_compliance_association',
        sa.Column('compliance_entity_id', sa.Integer(), nullable=False),
    )
    op.drop_constraint(
        'sis_compliance_association_compliance_company_id_fkey',
        'sis_compliance_association', type_='foreignkey',
    )
    op.create_foreign_key(
        'sis_compliance_association_compliance_entity_id_fkey',
        'sis_compliance_association', 'compliance_entities',
        ['compliance_entity_id'], ['id'],
    )
    op.drop_column('sis_compliance_association', 'compliance_company_id')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        'sis_compliance_association',
        sa.Column(
            'compliance_company_id', sa.INTEGER(),
            autoincrement=False, nullable=False,
        ),
    )
    op.drop_constraint(
        'sis_compliance_association_compliance_entity_id_fkey',
        'sis_compliance_association', type_='foreignkey',
    )
    op.create_foreign_key(
        'sis_compliance_association_compliance_company_id_fkey',
        'sis_compliance_association', 'compliance_entities',
        ['compliance_company_id'], ['id'],
    )
    op.drop_column('sis_compliance_association', 'compliance_entity_id')
    op.add_column(
        'compliance_sanctions',
        sa.Column(
            'company_id', sa.INTEGER(), autoincrement=False, nullable=False,
        ),
    )
    op.create_foreign_key(
        'company_sanctions_company_id_fkey', 'compliance_sanctions',
        'compliance_entities',
        ['company_id'], ['id'],
        onupdate='CASCADE', ondelete='CASCADE',
    )
    op.drop_constraint(
        'company_sanctions_compliance_id_unique', 'compliance_sanctions',
        type_='unique',
    )
    op.create_unique_constraint(
        'company_id_sanction_list_name', 'compliance_sanctions',
        ['company_id', 'sanction_list_name'],
    )
    op.drop_column('compliance_sanctions', 'compliance_id')
    op.drop_column('compliance_entities', 'entity_type')
    op.drop_table('compliance_entity_sanctions')

    entitytype.drop(op.get_bind(), checkfirst=False)
    # ### end Alembic commands ###
