"""Added companies

Revision ID: b16e052afa9c
Revises: 29cac3e2f325
Create Date: 2018-04-30 09:44:29.049634

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = 'b16e052afa9c'
down_revision = '29cac3e2f325'
branch_labels = None
depends_on = None


shipassociatetype = postgresql.ENUM(
    'GROUP_BENEFICIAL_OWNER', 'OPERATOR', 'REGISTERED_OWNER', 'SHIP_MANAGER',
    'TECHNICAL_MANAGER', name='shipassociatetype', create_type=False,
)


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        'compliance_companies',
        sa.Column('id', sa.Integer(), nullable=False),
        sa.Column('created', sa.DateTime(), nullable=False),
        sa.Column('updated', sa.DateTime(), nullable=False),
        sa.Column('compliance_id', sa.Integer(), nullable=False),
        sa.Column('name', sa.String(), nullable=True),
        sa.PrimaryKeyConstraint('id'),
        sa.UniqueConstraint('compliance_id'),
    )
    op.create_table(
        'sis_companies',
        sa.Column('id', sa.Integer(), nullable=False),
        sa.Column('created', sa.DateTime(), nullable=False),
        sa.Column('updated', sa.DateTime(), nullable=False),
        sa.Column('sis_code', sa.String(), nullable=False),
        sa.Column('name', sa.String(), nullable=True),
        sa.PrimaryKeyConstraint('id'),
        sa.UniqueConstraint('sis_code')
    )
    op.create_table(
        'sis_compliance_association',
        sa.Column('id', sa.Integer(), nullable=False),
        sa.Column('created', sa.DateTime(), nullable=False),
        sa.Column('updated', sa.DateTime(), nullable=False),
        sa.Column('sis_company_id', sa.Integer(), nullable=False),
        sa.Column('compliance_company_id', sa.Integer(), nullable=False),
        sa.ForeignKeyConstraint(
            ['compliance_company_id'], ['compliance_companies.id'],
        ),
        sa.ForeignKeyConstraint(
            ['sis_company_id'], ['sis_companies.id'],
        ),
        sa.PrimaryKeyConstraint(
            'id', 'sis_company_id', 'compliance_company_id',
        ),
    )
    op.add_column(
        'company_sanctions',
        sa.Column('company_id', sa.Integer(), nullable=False),
    )
    op.create_unique_constraint(
        'company_id_sanction_list_name', 'company_sanctions',
        ['company_id', 'sanction_list_name'],
    )
    op.drop_constraint(
        'ship_id_ship_associate_type_sanction_list_name',
        'company_sanctions', type_='unique',
    )
    op.drop_constraint(
        'company_sanctions_ship_id_fkey', 'company_sanctions',
        type_='foreignkey',
    )
    op.create_foreign_key(
        None, 'company_sanctions', 'compliance_companies',
        ['company_id'], ['id'], onupdate='CASCADE', ondelete='CASCADE',
    )
    op.drop_column('company_sanctions', 'ship_id')
    op.drop_column('company_sanctions', 'ship_associate_type')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        'company_sanctions',
        sa.Column(
            'ship_associate_type', shipassociatetype,
            autoincrement=False, nullable=False,
        ),
    )
    op.add_column(
        'company_sanctions',
        sa.Column(
            'ship_id', sa.INTEGER(),
            autoincrement=False, nullable=False,
        ),
    )
    op.drop_constraint(None, 'company_sanctions', type_='foreignkey')
    op.create_foreign_key(
        'company_sanctions_ship_id_fkey', 'company_sanctions', 'ships',
        ['ship_id'], ['id'],
        onupdate='CASCADE', ondelete='CASCADE',
    )
    op.create_unique_constraint(
        'ship_id_ship_associate_type_sanction_list_name', 'company_sanctions',
        ['ship_id', 'ship_associate_type', 'sanction_list_name'],
    )
    op.drop_constraint(
        'company_id_sanction_list_name', 'company_sanctions', type_='unique',
    )
    op.drop_column('company_sanctions', 'company_id')
    op.drop_table('sis_compliance_association')
    op.drop_table('sis_companies')
    op.drop_table('compliance_companies')
    # ### end Alembic commands ###
