"""Added ships indexes

Revision ID: b48c935a8fb6
Revises: 3b933a9de9dd
Create Date: 2018-08-29 08:47:45.117456

"""
from alembic import op


# revision identifiers, used by Alembic.
revision = 'b48c935a8fb6'
down_revision = '3b933a9de9dd'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index(
        op.f('ix_ships_country_id'), 'ships', ['country_id'], unique=False)
    op.create_index(
        op.f('ix_ships_type'), 'ships', ['type'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_ships_type'), table_name='ships')
    op.drop_index(op.f('ix_ships_country_id'), table_name='ships')
    # ### end Alembic commands ###
