"""Added compliance entity

Revision ID: b66f84ec8534
Revises: 2894d3615d1c
Create Date: 2018-05-16 21:03:21.363626

"""
from alembic import op

# revision identifiers, used by Alembic.
revision = 'b66f84ec8534'
down_revision = '2894d3615d1c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.rename_table('compliance_companies', 'compliance_entities')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.rename_table('compliance_entities', 'compliance_companies')
    # ### end Alembic commands ###
