"""Remove association id column

Revision ID: c365f35c7a87
Revises: b3ceee7863fd
Create Date: 2018-04-30 18:03:05.385939

"""
from alembic import op
import sqlalchemy as sa

# revision identifiers, used by Alembic.
revision = 'c365f35c7a87'
down_revision = 'b3ceee7863fd'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('sis_compliance_association', 'id')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        'sis_compliance_association',
        sa.Column('id', sa.INTEGER(), autoincrement=False, nullable=False),
    )
    # ### end Alembic commands ###
