"""Added bulk screenings indexes

Revision ID: c82b952ffa2a
Revises: 80d48a64e3c9
Create Date: 2018-11-12 15:56:38.225864

"""
from alembic import op


# revision identifiers, used by Alembic.
revision = 'c82b952ffa2a'
down_revision = '80d48a64e3c9'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index(
        op.f('ix_screenings_bulk_result'), 'screenings_bulk', ['result'],
        unique=False,
    )
    op.create_index(
        op.f('ix_screenings_bulk_status'), 'screenings_bulk', ['status'],
        unique=False,
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(
        op.f('ix_screenings_bulk_status'), table_name='screenings_bulk',
    )
    op.drop_index(
        op.f('ix_screenings_bulk_result'), table_name='screenings_bulk',
    )
    # ### end Alembic commands ###
