"""Added ship sanction code

Revision ID: c8bd06793331
Revises: 1b09215e4fba
Create Date: 2019-11-12 13:21:30.909787

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c8bd06793331'
down_revision = '1b09215e4fba'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        'ship_sanctions', sa.Column('code', sa.Integer(), nullable=False))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('ship_sanctions', 'code')
    # ### end Alembic commands ###
