"""Remove bulk screening unique constraint

Revision ID: cc7a85a92040
Revises: 5b0f58bba23d
Create Date: 2017-11-13 14:34:33.747535

"""
from alembic import op


# revision identifiers, used by Alembic.
revision = 'cc7a85a92040'
down_revision = '5b0f58bba23d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(
        'account_id_imo_id_unique', 'screenings_bulk', type_='unique')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint(
        'account_id_imo_id_unique', 'screenings_bulk', ['account_id', 'imo_id']
    )
    # ### end Alembic commands ###
