"""Added compliance sanctions

Revision ID: dde1cbcd8a23
Revises: b66f84ec8534
Create Date: 2018-05-17 11:01:21.937916

"""
from alembic import op

# revision identifiers, used by Alembic.
revision = 'dde1cbcd8a23'
down_revision = 'b66f84ec8534'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.rename_table('company_sanctions', 'compliance_sanctions')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.rename_table('compliance_sanctions', 'company_sanctions')
    # ### end Alembic commands ###
