"""Change bulk screening imo id to string

Revision ID: e0d7ce3f5f34
Revises: 11d0f3b945e2
Create Date: 2018-01-17 14:43:06.539862

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e0d7ce3f5f34'
down_revision = '11d0f3b945e2'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('screenings_bulk', 'imo_id', type_=sa.String())
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('screenings_bulk', 'imo_id', type_=sa.Integer())
    # ### end Alembic commands ###
