"""Added detained

Revision ID: e4c47d85e8e5
Revises: c2ac076fd1a5
Create Date: 2019-10-02 10:03:04.234408

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e4c47d85e8e5'
down_revision = 'c2ac076fd1a5'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        'ship_inspections',
        sa.Column(
            'detained', sa.Boolean(),
            nullable=False, server_default=sa.text("'f'"),
        ),
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('ship_inspections', 'detained')
    # ### end Alembic commands ###
