"""Update entity sanction compliance id

Revision ID: ec2812bcfe1e
Revises: 419bac7a74af
Create Date: 2018-10-15 12:56:07.698576

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ec2812bcfe1e'
down_revision = '419bac7a74af'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column(
        'compliance_entity_sanctions', 'compliance_id',
        existing_type=sa.INTEGER(), nullable=False,
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column(
        'compliance_entity_sanctions', 'compliance_id',
        existing_type=sa.INTEGER(), nullable=True,
    )
    # ### end Alembic commands ###
