"""Added more indexes

Revision ID: ee7a64f57058
Revises: b48c935a8fb6
Create Date: 2018-09-11 12:47:24.838742

"""
from alembic import op


# revision identifiers, used by Alembic.
revision = 'ee7a64f57058'
down_revision = 'b48c935a8fb6'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index(
        op.f('ix_company_associations_dst_id'),
        'company_associations', ['dst_id'],
        unique=False,
    )
    op.create_index(
        op.f('ix_company_associations_src_id'),
        'company_associations', ['src_id'],
        unique=False,
    )
    op.create_index(
        op.f('ix_compliance_entity_sanctions_compliance_entity_id'),
        'compliance_entity_sanctions', ['compliance_entity_id'],
        unique=False,
    )
    op.create_index(
        op.f('ix_compliance_entity_sanctions_compliance_sanction_id'),
        'compliance_entity_sanctions', ['compliance_sanction_id'],
        unique=False,
    )
    op.create_index(
        op.f('ix_screenings_ship_id'),
        'screenings', ['ship_id'],
        unique=False,
    )
    op.create_index(
        op.f('ix_screenings_bulk_account_id'),
        'screenings_bulk', ['account_id'],
        unique=False,
    )
    op.create_index(
        op.f('ix_screenings_history_screening_id'),
        'screenings_history', ['screening_id'],
        unique=False,
    )
    op.create_index(
        op.f('ix_ship_inspections_ship_id'),
        'ship_inspections', ['ship_id'],
        unique=False,
    )
    op.create_index(
        op.f('ix_ship_sanctions_ship_id'),
        'ship_sanctions', ['ship_id'],
        unique=False,
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(
        op.f('ix_ship_sanctions_ship_id'),
        table_name='ship_sanctions',
    )
    op.drop_index(
        op.f('ix_ship_inspections_ship_id'),
        table_name='ship_inspections',
    )
    op.drop_index(
        op.f('ix_screenings_history_screening_id'),
        table_name='screenings_history',
    )
    op.drop_index(
        op.f('ix_screenings_bulk_account_id'),
        table_name='screenings_bulk',
    )
    op.drop_index(
        op.f('ix_screenings_ship_id'),
        table_name='screenings',
    )
    op.drop_index(
        op.f('ix_compliance_entity_sanctions_compliance_sanction_id'),
        table_name='compliance_entity_sanctions',
    )
    op.drop_index(
        op.f('ix_compliance_entity_sanctions_compliance_entity_id'),
        table_name='compliance_entity_sanctions',
    )
    op.drop_index(
        op.f('ix_company_associations_src_id'),
        table_name='company_associations',
    )
    op.drop_index(
        op.f('ix_company_associations_dst_id'),
        table_name='company_associations',
    )
    # ### end Alembic commands ###
