# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-09-21 13:56
from __future__ import unicode_literals

from django.db import migrations


def add_periodic_tasks(apps, schema_editor):
    IntervalSchedule = apps.get_model("django_celery_beat", "IntervalSchedule")

    interval_1, _ = IntervalSchedule.objects.get_or_create(
        every=8, period='hours')
    interval_2, _ = IntervalSchedule.objects.get_or_create(
        every=5, period='minutes')

    CrontabSchedule = apps.get_model(
        "django_celery_beat", "CrontabSchedule")

    crontab_1, _ = CrontabSchedule.objects.get_or_create(hour='4', minute='0')

    PeriodicTask = apps.get_model("django_celery_beat", "PeriodicTask")

    PeriodicTask.objects.get_or_create(
        name='celery.backend_cleanup',
        task='celery.backend_cleanup',
        defaults={
            'crontab': crontab_1,
        }
    )
    PeriodicTask.objects.get_or_create(
        name='nightly-import',
        task='ships.tasks.synchronise_files',
        defaults={
            'interval': interval_1,
            'kwargs': (
                "{\r\n\t\"import_only\": null,\r\n\t\"exclude_files_re\": "
                "[\r\n\t\t\".*additional_data\",\r\n                \".*"
                "historical data.*\",\r\n                \".*movementdata_"
                "(.*201[5,4])\\\\.zip\"\r\n\t]\r\n}"
            ),
        },
    )
    PeriodicTask.objects.get_or_create(
        name='heartbeat',
        task='system.tasks.heartbeat',
        defaults={
            'interval': interval_2,
        },
    )


class Migration(migrations.Migration):

    dependencies = [
    ]

    operations = [
        migrations.RunPython(add_periodic_tasks),
    ]
