# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-12-20 09:55
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Flag',
            fields=[
                ('code', models.CharField(max_length=3, primary_key=True, serialize=False)),
                ('name', models.CharField(db_index=True, max_length=64, unique=True)),
                ('alt_name', models.CharField(blank=True, db_index=True, max_length=64, null=True)),
                ('world_region', models.CharField(max_length=32)),
                ('world_continent', models.CharField(max_length=16)),
                ('iso_3166_1_alpha_2', models.CharField(blank=True, db_index=True, max_length=50, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='LoadHistory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('started_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('finished_date', models.DateTimeField(blank=True, null=True)),
                ('status', models.CharField(choices=[('L', 'Loading'), ('S', 'Load Succeeded'), ('F', 'Load Failed')], default='L', max_length=1)),
            ],
            options={
                'verbose_name_plural': 'LoadHistory',
            },
        ),
        migrations.CreateModel(
            name='LoadStatus',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('filename', models.CharField(max_length=255)),
                ('started_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('finished_date', models.DateTimeField(blank=True, null=True)),
                ('status', models.CharField(choices=[('L', 'Loading'), ('S', 'Load Succeeded'), ('F', 'Load Failed')], max_length=1)),
                ('error_traceback', models.TextField(blank=True, null=True)),
                ('load_history', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='ships.LoadHistory')),
            ],
            options={
                'verbose_name_plural': 'LoadStatuses',
            },
        ),
        migrations.CreateModel(
            name='ShipData',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('imo_id', models.CharField(max_length=10, unique=True)),
                ('mmsi', models.CharField(blank=True, db_index=True, help_text='(9 digits)', max_length=10, null=True)),
                ('ship_name', models.CharField(blank=True, db_index=True, max_length=255, null=True)),
                ('shiptype_level_5', models.CharField(blank=True, db_index=True, max_length=255, null=True)),
                ('call_sign', models.CharField(blank=True, db_index=True, max_length=255, null=True)),
                ('flag_name', models.CharField(blank=True, db_index=True, max_length=255, null=True)),
                ('port_of_registry', models.CharField(blank=True, db_index=True, max_length=255, null=True)),
                ('ship_status', models.CharField(blank=True, max_length=255, null=True)),
                ('gross_tonnage', models.FloatField(blank=True, db_index=True, null=True)),
                ('length_overall_loa', models.FloatField(blank=True, db_index=True, null=True)),
                ('year_of_build', models.IntegerField(blank=True, db_index=True, null=True)),
                ('registered_owner', models.CharField(blank=True, db_index=True, max_length=255, null=True)),
                ('operator', models.CharField(blank=True, db_index=True, max_length=255, null=True)),
                ('ship_manager', models.CharField(blank=True, db_index=True, max_length=255, null=True)),
                ('technical_manager', models.CharField(blank=True, db_index=True, max_length=255, null=True)),
                ('group_beneficial_owner', models.CharField(blank=True, db_index=True, max_length=255, null=True)),
                ('data', models.TextField()),
                ('updated', models.DateTimeField(auto_now=True)),
                ('flag', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='ships.Flag')),
            ],
            options={
                'verbose_name': 'ship',
                'verbose_name_plural': 'ships',
            },
        ),
        migrations.CreateModel(
            name='ShipDefect',
            fields=[
                ('defect_id', models.IntegerField(primary_key=True, serialize=False)),
                ('defect_text', models.TextField(blank=True, null=True)),
                ('defect_code', models.CharField(blank=True, max_length=10, null=True)),
                ('action_1', models.CharField(blank=True, max_length=50, null=True)),
                ('action_2', models.CharField(blank=True, max_length=50, null=True)),
                ('action_3', models.CharField(blank=True, max_length=50, null=True)),
                ('other_action', models.TextField(blank=True, null=True)),
                ('recognised_org_resp_yn', models.CharField(blank=True, max_length=10, null=True)),
                ('recognised_org_resp_code', models.CharField(blank=True, max_length=10, null=True)),
                ('recognised_org_resp', models.CharField(blank=True, max_length=50, null=True)),
                ('other_recognised_org_resp', models.CharField(blank=True, max_length=10, null=True)),
                ('main_defect_code', models.CharField(blank=True, max_length=10, null=True)),
                ('main_defect_text', models.TextField(blank=True, null=True)),
                ('action_code_1', models.CharField(blank=True, max_length=10, null=True)),
                ('action_code_2', models.CharField(blank=True, max_length=10, null=True)),
                ('action_code_3', models.CharField(blank=True, max_length=10, null=True)),
                ('class_is_responsible', models.CharField(blank=True, max_length=10, null=True)),
                ('detention_reason_deficiency', models.CharField(blank=True, max_length=10, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='ShipImage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('imo_id', models.CharField(max_length=32)),
                ('source', models.CharField(blank=True, max_length=255, null=True)),
                ('taken_date', models.DateTimeField(blank=True, null=True)),
                ('url', models.URLField()),
                ('filename', models.CharField(max_length=255)),
                ('width', models.IntegerField()),
                ('height', models.IntegerField()),
                ('ship_data', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='ships.ShipData')),
            ],
        ),
        migrations.CreateModel(
            name='ShipInspection',
            fields=[
                ('inspection_id', models.CharField(max_length=50, primary_key=True, serialize=False)),
                ('imo_id', models.CharField(blank=True, max_length=10, null=True)),
                ('authorisation', models.CharField(blank=True, max_length=255, null=True)),
                ('ship_name', models.CharField(blank=True, max_length=255, null=True)),
                ('call_sign', models.CharField(blank=True, max_length=255, null=True)),
                ('flag_name', models.CharField(blank=True, max_length=255, null=True)),
                ('shipclass', models.CharField(blank=True, max_length=255, null=True)),
                ('shiptype', models.CharField(blank=True, max_length=255, null=True)),
                ('expanded_inspection', models.CharField(blank=True, max_length=255, null=True)),
                ('inspection_date', models.CharField(blank=True, max_length=50, null=True)),
                ('date_release', models.CharField(blank=True, max_length=50, null=True)),
                ('no_days_detained', models.CharField(blank=True, max_length=10, null=True)),
                ('port_name', models.CharField(blank=True, max_length=255, null=True)),
                ('country_name', models.CharField(blank=True, max_length=255, null=True)),
                ('owner', models.CharField(blank=True, max_length=255, null=True)),
                ('manager', models.TextField(blank=True, null=True)),
                ('charterer', models.CharField(blank=True, max_length=255, null=True)),
                ('cargo', models.CharField(blank=True, max_length=30, null=True)),
                ('detained', models.CharField(blank=True, max_length=10, null=True)),
                ('no_defects', models.CharField(blank=True, max_length=10, null=True)),
                ('source', models.CharField(blank=True, max_length=255, null=True)),
                ('gt', models.CharField(blank=True, max_length=50, null=True)),
                ('dwt', models.CharField(blank=True, max_length=50, null=True)),
                ('yob', models.CharField(blank=True, max_length=10, null=True)),
                ('other_inspection_type', models.CharField(blank=True, max_length=255, null=True)),
                ('number_part_days_detained', models.CharField(blank=True, max_length=10, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='ShipMovement',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('imo_id', models.CharField(blank=True, db_index=True, max_length=10, null=True)),
                ('arrival_date', models.DateField(blank=True, max_length=127, null=True)),
                ('timestamp', models.DateTimeField(blank=True, db_index=True, null=True)),
                ('ihs_id', models.CharField(blank=True, db_index=True, max_length=127, null=True)),
                ('country_name', models.CharField(blank=True, max_length=127, null=True)),
                ('ihs_creation_date', models.DateTimeField(blank=True, null=True)),
                ('destination_port', models.CharField(blank=True, max_length=127, null=True)),
                ('estimated_time_of_arrival', models.DateTimeField(blank=True, null=True)),
                ('hours_in_port', models.IntegerField(blank=True, null=True)),
                ('last_port_of_call_arrival_date', models.DateTimeField(blank=True, null=True)),
                ('last_port_of_call_code', models.CharField(blank=True, max_length=127, null=True)),
                ('last_port_of_call_country', models.CharField(blank=True, max_length=127, null=True)),
                ('last_port_of_call_country_code', models.CharField(blank=True, max_length=127, null=True)),
                ('last_port_of_call_name', models.CharField(blank=True, max_length=127, null=True)),
                ('last_port_of_call_sail_date', models.DateTimeField(blank=True, null=True)),
                ('movement_type', models.CharField(blank=True, max_length=127, null=True)),
                ('port_name', models.CharField(blank=True, max_length=127, null=True)),
                ('ihs_port_geo_id', models.CharField(blank=True, max_length=127, null=True)),
                ('ihs_port_id', models.CharField(blank=True, max_length=127, null=True)),
                ('latitude', models.DecimalField(blank=True, decimal_places=6, max_digits=8, null=True)),
                ('longitude', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True)),
                ('sail_date', models.DateField(blank=True, null=True)),
                ('sail_date_full', models.DateTimeField(blank=True, null=True)),
                ('ship_name', models.CharField(blank=True, max_length=127, null=True)),
                ('ship_type', models.CharField(blank=True, max_length=127, null=True)),
                ('creation_date', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.AlterUniqueTogether(
            name='shipmovement',
            unique_together=set([('imo_id', 'timestamp', 'ihs_id')]),
        ),
        migrations.AddField(
            model_name='shipdefect',
            name='inspection',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='defects', to='ships.ShipInspection'),
        ),
    ]
