# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-01-22 13:36
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ships', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='MMSIHistory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('modified', models.DateTimeField(auto_now=True)),
                ('imo_number', models.CharField(max_length=7)),
                ('mmsi', models.CharField(max_length=15)),
                ('effective_from', models.DateTimeField(auto_now_add=True)),
                ('effective_to', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'verbose_name': 'mmsi_history',
                'verbose_name_plural': 'MMSI Histories',
            },
        ),
        migrations.AddField(
            model_name='shipmovement',
            name='extra_data',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterUniqueTogether(
            name='mmsihistory',
            unique_together=set([('imo_number', 'mmsi')]),
        ),
    ]
