# -*- coding: utf-8 -*-
# Generated by Django 1.11.20 on 2019-03-07 16:17
from __future__ import unicode_literals

from django.db import migrations, models
import django.contrib.postgres.fields.jsonb


class Migration(migrations.Migration):

    dependencies = [
        ('ships', '0003_auto_20190301_1511'),
    ]

    operations = [
        migrations.AddField(
            model_name='shipdatamanualchange',
            name='expired',
            field=models.BooleanField(default=False),
        ),
        migrations.RemoveField(
            model_name='shipdatamanualchange',
            name='changed_data',
        ),
        migrations.AddField(
            model_name='shipdatamanualchange',
            name='new_data',
            field=django.contrib.postgres.fields.jsonb.JSONField(default={}),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='shipdatamanualchange',
            name='old_data',
            field=django.contrib.postgres.fields.jsonb.JSONField(default={}),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='shipdatamanualchange',
            name='reason',
            field=models.CharField(default='', max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='shipdata',
            name='original_data',
            field=django.contrib.postgres.fields.jsonb.JSONField(
                default={}, max_length=255,
                null=True, blank=True),
            preserve_default=False,
        ),
    ]
