# -*- coding: utf-8 -*-
# Generated by Django 1.11.20 on 2019-04-02 15:21
from __future__ import unicode_literals

import django.contrib.postgres.fields.jsonb
from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('ships', '0004_shipdatamanualchange_expired'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mmsihistory',
            name='effective_from',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
