# -*- coding: utf-8 -*-
# Generated by Django 1.11.29 on 2022-01-31 13:29
from __future__ import unicode_literals

import django.contrib.postgres.fields.jsonb
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ships', '0007_auto_20190510_0913'),
    ]

    operations = [
        migrations.CreateModel(
            name='ShipDataHistory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField()),
                ('imo_id', models.CharField(max_length=10)),
                ('mmsi', models.CharField(blank=True, db_index=True, help_text='(9 digits)', max_length=10, null=True)),
                ('ship_name', models.CharField(blank=True, db_index=True, max_length=255, null=True)),
                ('shiptype_level_5', models.CharField(blank=True, db_index=True, max_length=255, null=True)),
                ('call_sign', models.CharField(blank=True, db_index=True, max_length=255, null=True)),
                ('flag_name', models.CharField(blank=True, db_index=True, max_length=255, null=True)),
                ('flag_effective_date', models.CharField(blank=True, max_length=10, null=True)),
                ('port_of_registry', models.CharField(blank=True, db_index=True, max_length=255, null=True)),
                ('ship_status', models.CharField(blank=True, max_length=255, null=True)),
                ('gross_tonnage', models.FloatField(blank=True, db_index=True, null=True)),
                ('length_overall_loa', models.FloatField(blank=True, db_index=True, null=True)),
                ('year_of_build', models.IntegerField(blank=True, db_index=True, null=True)),
                ('registered_owner', models.CharField(blank=True, db_index=True, max_length=255, null=True)),
                ('registered_owner_code', models.IntegerField(blank=True, db_index=True, null=True)),
                ('registered_owner_registration_country', models.CharField(blank=True, db_index=True, max_length=255, null=True)),
                ('registered_owner_control_country', models.CharField(blank=True, db_index=True, max_length=255, null=True)),
                ('registered_owner_domicile_country', models.CharField(blank=True, db_index=True, max_length=255, null=True)),
                ('registered_owner_domicile_code', models.CharField(blank=True, db_index=True, max_length=3, null=True)),
                ('operator', models.CharField(blank=True, db_index=True, max_length=255, null=True)),
                ('operator_code', models.IntegerField(blank=True, db_index=True, null=True)),
                ('operator_registration_country', models.CharField(blank=True, db_index=True, max_length=255, null=True)),
                ('operator_control_country', models.CharField(blank=True, db_index=True, max_length=255, null=True)),
                ('operator_domicile_country', models.CharField(blank=True, db_index=True, max_length=255, null=True)),
                ('operator_domicile_code', models.CharField(blank=True, db_index=True, max_length=3, null=True)),
                ('ship_manager', models.CharField(blank=True, db_index=True, max_length=255, null=True)),
                ('ship_manager_code', models.IntegerField(blank=True, db_index=True, null=True)),
                ('ship_manager_registration_country', models.CharField(blank=True, db_index=True, max_length=255, null=True)),
                ('ship_manager_control_country', models.CharField(blank=True, db_index=True, max_length=255, null=True)),
                ('ship_manager_domicile_country', models.CharField(blank=True, db_index=True, max_length=255, null=True)),
                ('ship_manager_domicile_code', models.CharField(blank=True, db_index=True, max_length=3, null=True)),
                ('technical_manager', models.CharField(blank=True, db_index=True, max_length=255, null=True)),
                ('technical_manager_code', models.IntegerField(blank=True, db_index=True, null=True)),
                ('technical_manager_registration_country', models.CharField(blank=True, db_index=True, max_length=255, null=True)),
                ('technical_manager_control_country', models.CharField(blank=True, db_index=True, max_length=255, null=True)),
                ('technical_manager_domicile_country', models.CharField(blank=True, db_index=True, max_length=255, null=True)),
                ('technical_manager_domicile_code', models.CharField(blank=True, db_index=True, max_length=3, null=True)),
                ('group_beneficial_owner', models.CharField(blank=True, db_index=True, max_length=255, null=True)),
                ('group_beneficial_owner_code', models.IntegerField(blank=True, db_index=True, null=True)),
                ('group_beneficial_owner_registration_country', models.CharField(blank=True, db_index=True, max_length=255, null=True)),
                ('group_beneficial_owner_control_country', models.CharField(blank=True, db_index=True, max_length=255, null=True)),
                ('group_beneficial_owner_domicile_country', models.CharField(blank=True, db_index=True, max_length=255, null=True)),
                ('group_beneficial_owner_domicile_code', models.CharField(blank=True, db_index=True, max_length=3, null=True)),
                ('data', django.contrib.postgres.fields.jsonb.JSONField()),
            ],
            options={
                'verbose_name': 'ship_history',
                'verbose_name_plural': 'ships history',
            },
        ),
        migrations.AlterUniqueTogether(
            name='shipdatahistory',
            unique_together=set([('timestamp', 'imo_id')]),
        ),
    ]
