# -*- coding: utf-8 -*-
# Generated by Django 1.11.29 on 2022-02-28 19:54
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ships', '0010_companyhistory'),
    ]

    operations = [
        migrations.AddField(
            model_name='flaghistory',
            name='flag',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='ships.Flag'),
        ),
    ]
