# -*- coding: utf-8 -*-
# Generated by Django 1.11.29 on 2022-03-16 19:10
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ships', '0011_flaghistory_flag'),
    ]

    operations = [
        migrations.AlterField(
            model_name='flaghistory',
            name='flag',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='ships.Flag'),
        ),
        migrations.AlterField(
            model_name='flaghistory',
            name='flag_effective_date',
            field=models.DateTimeField(),
        ),
        migrations.AlterField(
            model_name='flaghistory',
            name='flag_name',
            field=models.CharField(db_index=True, max_length=255),
        ),
        migrations.AlterField(
            model_name='flaghistory',
            name='imo_id',
            field=models.CharField(db_index=True, max_length=10),
        ),
    ]
