# Generated by Django 2.2.25 on 2022-04-11 15:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ships', '0012_flag_effective_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='companyhistory',
            name='association_type',
            field=models.CharField(
                blank=True,
                choices=[
                    ('REGISTERED_OWNER', 'Registered Owner'),
                    ('OPERATOR', 'Operator'),
                    ('SHIP_MANAGER', 'Ship Manager'),
                    ('TECHNICAL_MANAGER', 'Technical Manager'),
                    ('GROUP_BENEFICIAL_OWNER', 'Group Beneficial Owner'),
                ],
                max_length=30,
                null=True,
                verbose_name='Association type',
            ),
        ),
    ]
