# Generated by Django 2.2.25 on 2022-05-05 11:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ships', '0014_ship_data_original_data_default_value'),
    ]

    operations = [
        migrations.AlterField(
            model_name='companyhistory',
            name='ignore',
            field=models.BooleanField(db_index=True, default=False),
        ),
        migrations.AlterField(
            model_name='companyhistory',
            name='imo_id',
            field=models.CharField(db_index=True, max_length=10),
        ),
        migrations.AlterField(
            model_name='flaghistory',
            name='ignore',
            field=models.BooleanField(db_index=True, default=False),
        ),
    ]
