# Generated by Django 2.2.25 on 2022-05-20 11:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ships', '0015_history_models_indexes'),
    ]

    operations = [
        migrations.AddField(
            model_name='companyhistory',
            name='effective_date',
            field=models.DateTimeField(),
            preserve_default=False,
        ),
    ]
