# Generated by Django 2.2.25 on 2022-05-27 01:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ships', '0016_company_effective_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shipdatahistory',
            name='imo_id',
            field=models.CharField(db_index=True, max_length=10),
        ),
    ]
