# Generated by Django 2.2.25 on 2022-07-21 16:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ships', '0018_associaton_type_index'),
    ]

    operations = [
        migrations.RunSQL(
            sql="""
            UPDATE ships_companyhistory 
            SET company_name='  Unknown', company_code=9991001 
            WHERE company_name='';
            """,
            reverse_sql=migrations.RunSQL.noop
        )
    ]
