# Generated by Django 2.2.25 on 2022-08-16 11:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ships', '0019_blank_companies'),
    ]

    operations = [
        migrations.RunSQL(
            sql="""
            UPDATE ships_companyhistory 
            SET company_code=9991001 
            WHERE company_name='  Unknown';
            """,
            reverse_sql=migrations.RunSQL.noop
        )
    ]
