repos:
  - repo: https://github.com/pre-commit/mirrors-eslint
    rev: "v8.29.0"
    hooks:
      - id: eslint
        files: \.[jt]sx?$
        types: [file]
        args: ["--fix"]
        additional_dependencies:
          - "eslint@8.29.0"
          - "@typescript-eslint/eslint-plugin"
          - "eslint-plugin-prettier@4.2.1"
          - "eslint-config-prettier"
          - "@angular-eslint/eslint-plugin"
          - "@angular-eslint/eslint-plugin-template"
          - "@typescript-eslint/parser"
          - "eslint-plugin-node"
          - "eslint-plugin-import"
          - "@babel/eslint-parser"

  # NOTE: only used for files not handle by eslint
  - repo: https://github.com/pre-commit/mirrors-prettier
    rev: "v2.7.1"
    hooks:
      - id: prettier
        exclude: |
          (?x)(
              ^.*.json |
              ^.*.yaml |
              ^.*.yml |
              \.[jt]sx?$
          )
