repos:
  - repo: https://github.com/pre-commit/mirrors-prettier
    rev: v2.7.1
    hooks:
      - id: prettier
        args:
          - --parser
          - yaml
          - --prose-wrap
          - preserve
        types:
          - yaml
