/*
    This query has been designed to replicate a historic export for globavista.
*/
SELECT
    sd.id id,
    null ihs_id,
    sd.imo_id imo_id,
    sd.ship_name ship_name,
    sd.call_sign call_sign,
    sd.mmsi mmsi,
    sd.data->'shiptype_level_5' shiptype_level_5,
    sd.ship_status ship_status,
    sd.data->'port_of_registry' port_of_registry,
    data->'flag_alt_name' flag_alt_name,
    f.code flag_code,
    data->'flag_effective_date' flag_effective_date,
    f.iso_3166_1_alpha_2 flag_iso_3166_1_alpha_2,
    f.name flag_name,
    f.world_continent flag_world_continent,
    f.world_region flag_world_region,
    data->'classification_society' classification_society,
    sd.data->'gross_tonnage' gross_tonnage,
    sd.data->'deadweight' deadweight,
    sd.length_overall_loa length_overall_loa,
    sd.data->'breadth' breadth,
    sd.data->'depth' depth,
    sd.data->'displacement' displacement,
    sd.data->'draught' draught,
    sd.data->'speed' speed,
    data->'bareboat_charter_company' bareboat_charter_company,
    data->'bareboat_charter_country_of_control' bareboat_charter_country_of_control,
    data->'bareboat_charter_country_of_domicile' bareboat_charter_country_of_domicile,
    data->'bareboat_charter_country_of_registration' bareboat_charter_country_of_registration,
    data->'bareboat_charter_effective_date' bareboat_charter_effective_date,
    sd.data->'doc_company' doc_company,
    data->'doc_company_country_of_domicile' doc_company_country_of_domicile,
    data->'doc_company_country_of_domicilecode' doc_company_country_of_domicilecode,
    data->'doc_country_of_control' doc_country_of_control,
    data->'doc_country_of_registration' doc_country_of_registration,
    data->'document_of_compliance_doc_company_code' document_of_compliance_doc_company_code,
    data->'group_beneficial_owner' group_beneficial_owner,
    data->'group_beneficial_owner_company_code' group_beneficial_owner_company_code,
    data->'group_beneficial_owner_country_of_control' group_beneficial_owner_country_of_control,
    data->'group_beneficial_owner_country_of_domicile' group_beneficial_owner_country_of_domicile,
    data->'group_beneficial_owner_country_of_domicile_code' group_beneficial_owner_country_of_domicile_code,
    data->'group_beneficial_owner_country_of_registration' group_beneficial_owner_country_of_registration,
    data->'operator' "operator",
    data->'operator_company_code' "operator_company_code",
    data->'operator_country_of_control' "operator_country_of_control",
    data->'operator_country_of_domicile_code' "operator_country_of_domicile_code",
    data->'operator_country_of_domicile_name' "operator_country_of_domicile_name",
    data->'operator_country_of_registration' "operator_country_of_registration",
    data->'registered_owner' registered_owner,
    data->'registered_owner_code' registered_owner_code,
    data->'registered_owner_country_of_control' registered_owner_country_of_control,
    data->'registered_owner_country_of_domicile' registered_owner_country_of_domicile,
    data->'registered_owner_country_of_domicile_code' registered_owner_country_of_domicile_code,
    data->'registered_owner_country_of_registration' registered_owner_country_of_registration,
    data->'safety_management_certificate_date_expires' safety_management_certificate_date_expires,
    data->'safety_management_certificate_date_issued' safety_management_certificate_date_issued,
    data->'safety_management_certificate_doc_company' safety_management_certificate_doc_company,
    data->'safety_management_certificate_issuer' safety_management_certificate_issuer,
    data->'ship_manager' ship_manager,
    data->'ship_manager_company_code' ship_manager_company_code,
    data->'ship_manager_country_of_control' ship_manager_country_of_control,
    data->'ship_manager_country_of_domicile_code' ship_manager_country_of_domicile_code,
    data->'ship_manager_country_of_domicile_name' ship_manager_country_of_domicile_name,
    data->'ship_manager_country_of_registration' ship_manager_country_of_registration,
    data->'technical_manager' technical_manager,
    data->'technical_manager_code' technical_manager_code,
    data->'technical_manager_country_of_control' technical_manager_country_of_control,
    data->'technical_manager_country_of_domicile' technical_manager_country_of_domicile,
    data->'technical_manager_country_of_domicile_code' technical_manager_country_of_domicile_code,
    data->'technical_manager_country_of_registration' technical_manager_country_of_registration,
    null thumbnail,
    null image,
    sd.updated updated,
    sd.data->'shipbuilder' shipbuilder,
    sd.data->'country_of_build' country_of_build,
    sd.year_of_build year_of_build,
    sd.data->'stat_code_5' stat_code_5
FROM
    ships_shipdata sd
JOIN
    ships_flag f
    ON
        f.code = sd.flag_id
