REPO_MANAGER_DIRECTORY_PATH = ".repomanager/"

CACHE_PATH = REPO_MANAGER_DIRECTORY_PATH + "cache/"
STATE_PATH = REPO_MANAGER_DIRECTORY_PATH + "state/"

CONFIG_REPO_GLOBAL_CONFIG_FILE_NAME = "config.yml"
CONFIG_REPO_PROFILE_CONFIG_FILE_NAME = "repomanager.yml"
