repos:
  - repo: local
    hooks:
      - id: tslint
        name: tslint
        entry: tslint
        language: node
        files: \.[jt]sx?$
        types: [file]
        args: []
        require_serial: false
        minimum_pre_commit_version: "0"
        additional_dependencies:
          - "tslint@6.1.3"
          - "tslint-eslint-rules@5.4.0"
          - "tslint-config-prettier@1.18.0"
          - "prettier"
