name: publish python library
on:
  workflow_run:
    workflows: [version]
    types:
      - completed

# FIXME review
permissions:
  id-token: write # jwt token
  actions: read # gh actions
  contents: write # repo

jobs:
  # FIXME make reusable action (for other workflows linked to version workflow)
  check:
    outputs:
      new_version: ${{ steps.check-version.outputs.new-version }}
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v3
      - name: Get tags
        run: git fetch --prune --unshallow --tags
      - name: Check if new version
        id: check-version
        run: |
          if [ $(git tag --points-at HEAD | wc -l) -gt 1 ]; then
            echo "Got more than one tag, was not expecting this, bumming out..."
            exit 1
          fi

          # Set new version (or empty string)
          VERSION=$(git tag --points-at HEAD)
          echo VERSION:$VERSION
          echo "::set-output name=new-version::${VERSION}"

  publish:
    needs: check
    if: needs.check.outputs.new_version
    runs-on: ubuntu-latest
    env:
      AWS_ACCOUNT_ID: ${{ secrets.POLESTAR_TOOLS }}
      AWS_ACCOUNT_NAME: polestar-tools
      AWS_DEFAULT_REGION: us-east-1
      PS_PYTHON_REPO_NAME: ps-python
    steps:
      - name: Checkout repo
        uses: actions/checkout@v3
        with:
          lfs: true

      - name: Set up python
        uses: actions/setup-python@v3
        with:
          python-version: "3.8"
      - name: install poetry
        run: pip install poetry
        shell: bash

      - name: Configure AWS credentials from tools account
        uses: aws-actions/configure-aws-credentials@v1
        with:
          role-to-assume: arn:aws:iam::${{ secrets.POLESTAR_TOOLS }}:role/github-publish-role
          aws-region: us-east-1

      - name: Check versions match
        run: |
          VERSION=${{ needs.check.outputs.new_version }}

          echo $VERSION
          if $(poetry version --short) != $VERSION; then
            echo "Version mismatch".
            exit 1
          fi

          echo "VERSION=$VERSION" >> $GITHUB_ENV

      - name: Get CodeArtifact url
        run: echo "CODEARTIFACT_REPOSITORY_URL=$(aws codeartifact get-repository-endpoint --domain $AWS_ACCOUNT_NAME --domain-owner $AWS_ACCOUNT_ID --repository $PS_PYTHON_REPO_NAME --format pypi --query repositoryEndpoint --output text)" >> $GITHUB_ENV

      - name: Get CodeArtifact token
        run: echo "CODEARTIFACT_AUTH_TOKEN=$(aws codeartifact get-authorization-token --domain $AWS_ACCOUNT_NAME --domain-owner $AWS_ACCOUNT_ID --query authorizationToken --output text)" >> $GITHUB_ENV

      - run: poetry config repositories.$PS_PYTHON_REPO_NAME $CODEARTIFACT_REPOSITORY_URL
      - run: poetry config http-basic.$PS_PYTHON_REPO_NAME aws $CODEARTIFACT_AUTH_TOKEN

      - name: Optional makefile pre-publish hook
        run: |
          if grep "publish-python-library-poetry-pre-publish" Makefile; then
            echo "Running pre-publish hook"
            make publish-python-library-poetry-pre-publish
          else
            echo "No pre-publish hook detected"
          fi

      - name: Build and publish
        run: poetry publish --build --repository $PS_PYTHON_REPO_NAME
