# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-12-20 09:55
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Country',
            fields=[
                ('code', models.CharField(max_length=3, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=64, unique=True)),
                ('world_region', models.CharField(blank=True, max_length=32, null=True)),
                ('world_continent', models.CharField(blank=True, max_length=16, null=True)),
                ('flag_registry', models.IntegerField(blank=True, null=True)),
                ('flag_lrit_identifier', models.IntegerField(blank=True, null=True)),
                ('flag_name', models.CharField(blank=True, max_length=128, null=True)),
                ('iso_3166_1_alpha_2', models.CharField(blank=True, max_length=50, null=True)),
            ],
            options={
                'verbose_name_plural': 'countries',
                'ordering': ('name',),
            },
        ),
        migrations.CreateModel(
            name='CountryAlternateName',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=64, unique=True)),
                ('country', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='alternate_names', to='ports.Country')),
            ],
            options={
                'verbose_name': 'alternate name',
                'verbose_name_plural': 'alternate names',
            },
        ),
        migrations.CreateModel(
            name='Port',
            fields=[
                ('code', models.CharField(max_length=8, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=64)),
                ('latitude', models.FloatField(blank=True, null=True)),
                ('longitude', models.FloatField(blank=True, null=True)),
                ('scale', models.FloatField(blank=True, null=True)),
                ('country', models.ForeignKey(default='1', on_delete=django.db.models.deletion.CASCADE, to='ports.Country')),
            ],
            options={
                'ordering': ('name',),
            },
        ),
        migrations.CreateModel(
            name='PortAlternateName',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=64)),
                ('country', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ports.Country')),
                ('port', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='alternate_names', to='ports.Port')),
            ],
            options={
                'verbose_name': 'alternate name',
                'verbose_name_plural': 'alternate names',
            },
        ),
        migrations.AlterUniqueTogether(
            name='portalternatename',
            unique_together=set([('country', 'name')]),
        ),
    ]
